Use hostnames for clustering
canonical/alertmanager-k8s-operator pull request #55
Opened 2022-02-10 03:16 UTC by dstathis

2022-02-10 10:02 UTC, mmanciop commented
What issue does this PR solve?

2022-02-10 19:22 UTC, mmanciop commented
> > What issue does this PR solve?
> 
> @mmanciop It avoids waiting 5 minutes (or longer) for update-status when the IP address is not ready on time.

Nice explanation. I wish it would be in the commit message.

2022-02-15 18:50 UTC, sed-i approved these changes

2022-02-15 18:52 UTC, rbarry82 requested changes

2022-02-15 18:52 UTC, rbarry82 commented on src/charm.py
> +        return f"{pod_name}.{self.app.name}-endpoints.{self.model.name}.svc.cluster.local"
See my comment in MM. This is not reliable. Use `socket.getfqdn()`

2022-02-15 23:02 UTC, rbarry82 approved these changes

2022-02-16 07:20 UTC, merged